#!/bin/bash
alias "__"="clear ; exec bash"
alias ".."="cd .."
alias "nano"="nano -mDEgl -T 4"

alias "lx"="ls -lfXrAp"
alias "ll"="ls -lah"
alias "la"="ls -a"

# GIT aliases
alias gita="git add ."
alias gitc="git commit -m"
alias gitp="git push"

# tmux
alias tmux="tmux -f $HOME/.bash/tmux.conf"
