#!/bin/bash

if [ -d $HOME/.bash/bin ]; then
    export PATH=$HOME/.bash/bin:$PATH
fi

export HISTFILE=$HOME/.bash/bash_history.log
export HISTSIZE=11000
export HISTFILESIZE=11000
export HISTTIMEFORMAT="%F %T "
export PROMPT_COMMAND='history -a'
